version: '3'
services:
  #haProxy:
  #  image: haproxy:2.3
  #  container_name: proxy_inverso
  #  sysctls:
  #    - net.ipv4.ip_unprivileged_port_start=0
  #  restart: always
  #  tty: true
  #  ports:
  #    - "80:8080"
  #    - "8404:8404"
  #    - "443:443"
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - "./haproxy:/usr/local/etc/haproxy:rw"
  #    - "./ssl:/ssl"
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    ports:
      - 80:80
      - 9080:9080
      - 9081:9081
      #- 9082:9082
      #- 9083:9083
      #- 9084:9084
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./code:/var/www/html
      - ./nginx/config/default:/etc/nginx/conf.d/default.conf:rw
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/config/logs:/var/log/nginx

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: sica-app
    container_name: apps
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./code:/var/www/html
      - ./php/general_config/openssl.cnf:/etc/ssl/openssl.cnf
    labels:
    - "traefik.http.routers.app.rule=Host(`app.localhost`)"
    expose:
      - 9000

  db:
    image: mariadb:10.7.1
    env_file:
      - .env
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/etc:/etc/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD_ROOT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # networks:
    #   red-sica:
    #     ipv4_address: 172.18.0.4

# networks:
#   red-sica:
#     ipam:
#       driver: default
#       config:
#         - subnet: "172.18.0.0/16"
